### ISSUE TITLE
hi yury i keep getting error in omprog

### ISSUE THREAD

**Issue by kahfiAG** [jay7x/rsyslog_exporter_py#1]
when i installed using your guidelines , it's says "omprog is uknown". is there anyway to resolve this ?thanks in advance : )

**Comment by jay7x** [comment]
Could you please paste your config and `rsyslog -N 1` output (this command parses config and have version in it's output as well).

**Comment by kahfiAG** [comment]
when rsyslog -N 1
`rsyslogd -N 1
rsyslogd: version 8.2004.0.26bd4b61bbad, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: module name 'omprog' is unknown [v8.2004.0.26bd4b61bbad try https://www.rsyslog.com/e/2209 ]
rsyslogd: error during parsing file /etc/rsyslog.d/impstats.conf, on or before line 16: errors occured in file '/etc/rsyslog.d/impstats.conf' around line 16 [v8.2004.0.26bd4b61bbad try https://www.rsyslog.com/e/2207 ]
`
ubuntu 16.04  
rsyslogd  8.2004.0.26bd4b61bbad (aka 2020.04) compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	systemd support:			Yes
	Config file:				/etc/rsyslog.conf
	PID file:				/var/run/rsyslogd.pid

thank you so much for your response mr yury

**Comment by jay7x** [comment]
Could you please show output `dpkg -L rsyslog | grep omprog`? For me on ubuntu 16.04 it is `/usr/lib/rsyslog/omprog.so`.

**Comment by jay7x** [comment]
Found it. Somehow I missed `module(load="omprog")`. Will update README now! Could you please add this line and recheck it again?

**Comment by jay7x** [comment]
Closing by timeout :)

**Comment by kahfiAG** [comment]
worked liked a charm, thank you so much mr yuri : )
